services:
    php:
        image: rnmp_php
        networks:
            - frontend
            - backend
        volumes: 
            - D:\data\projects:/srv/http
            - D:\data\docker\rnmp\conf/php/php.ini:/usr/local/etc/php/php.ini
            - D:\data\docker\rnmp\conf/php/php-fpm.d:/usr/local/etc/php-fpm.d
            - D:\data\docker\rnmp\log/php:/var/log/php
        deploy:
          resources:
            limits:
              memory: 4096m
    nginx:
        image: nginx
        networks:
            - frontend
        volumes: 
            - D:\data\projects:/srv/http
            - D:\data\docker\rnmp\conf/nginx/conf.d:/etc/nginx/conf.d
            - D:\data\docker\rnmp\conf/nginx/nginx.conf:/etc/nginx/nginx.conf
            - D:\data\docker\rnmp\log/nginx:/var/log/nginx
        deploy:
          resources:
            limits:
              memory: 1024m
    master-mysql:
        image: mysql
        networks:
            - backend
        volumes:
            - D:\data\docker\rnmp\data/mysql/master:/var/lib/mysql
            - D:\data\docker\rnmp\conf/mysql/master:/etc/mysql/conf.d
            - D:\data\docker\rnmp\log/mysql/master:/var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        deploy:
          resources:
            limits:
              memory: 2048m
    slave-mysql:
        image: mysql
        networks:
            - backend
        volumes:
            - D:\data\docker\rnmp\data/mysql/slave:/var/lib/mysql
            - D:\data\docker\rnmp\conf/mysql/slave:/etc/mysql/conf.d
            - D:\data\docker\rnmp\log/mysql/slave:/var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        deploy:
          resources:
            limits:
              memory: 2048m
    redis:
        image: redis
        volumes:
            - D:\data\docker\rnmp\conf/redis/:/usr/local/etc/redis
            - D:\data\docker\rnmp\data/redis:/data
            - D:\data\docker\rnmp\log/redis:/var/log/redis
        networks:
            - backend
        command: ["redis-server","/usr/local/etc/redis/redis.conf"]
        restart: always
        deploy:
          resources:
            limits:
              memory: 1024m
networks:
    frontend:
    backend:
version: "3"